name: test
on: [push]
jobs:
  test:
    env:
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # - name: Install deps and build (with cache)
      #   uses: bahmutov/npm-install@v1
      - run: yarn install

      - name: Next.js cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/yarn.lock') }}-nextjs

      - run: yarn lint
      - run: yarn build
      - run: yarn test

